### ISSUE TITLE
Add slug-based URLs for pathways

### ISSUE THREAD

**Issue by allanhaggett** [allanhaggett/learning-curator#10]
Write a migration to add a slug field on the pathway table, and update controllers so that /pathways/view/1 can also be requested as /pathways/personal-development (or something like that)

**Comment by MariaChenBCGov** [comment]
- [ ] Deploy
- [ ] Team tested
- [ ] External user tested

**Comment by allanhaggett** [comment]
Commit d6210f8df67c3f007c717c85675e7e8bef1e4dec
Holding off on fully implementing this in the prototype for now until we make the big platform decision. I've laid the groundwork here for slug-based pathways, but am not implementing them on "this side" of things; if we move forward on this platform, the pathways/steps/activities base pages will be generated in a publishing pipeline where we can implement the slug-based routes there. Having these "clean URLs" implemented on the curator/author ("Curator Headless CMS") side is too much work to implement for zero real benefit.
