### ISSUE TITLE
User Analytics

### ISSUE THREAD

**Issue by MariaChenBCGov** [allanhaggett/learning-curator#130]
- [x] contact Jeremy V. @Work for Matomo setup
- [x] Approach management about analytics in general and offer to help set this up
- [x] Inquire further with Jeremy
- [x] Inquire again with Jeremy about status of Matomo on OpenShift End of August

**Comment by MariaChenBCGov** [comment]
May 26: I wrote this morning: "Hi Jeremy,

I hope this finds you well 😊

In the beforetimes (December '19), we met regarding the Curation application (via CakePHP) that the Learning Centre is developing. You had mentioned that you might be standing up an instance of Matomo Analytics, and that we might be able to make use of it for some of our projects if that happened.

I understand that, not only has the landscape changed dramatically, but that there were some technical issues in working with the OpenShift platform that may have affected your plans in this area. Is Matomo still a thing on your radar?

Thanks for your time!

Allan"

**Comment by MariaChenBCGov** [comment]
Jun 11: Have not heard back from Jeremy at this point. We should meet with David to discuss options moving forward. I would like to reach out to Jeremy again and offer to help them with the project if I can. It would be a massive benefit for us to use not just on this project, but every other web project. We NEED these anayltics.
Jun 30: I'm sorry I missed the comments on this, Allan. I can try setting up a meeting with Jeremy and David.
Jul 14: We met with Jeremy yesterday and he said that Matomo is back on the table (after being removed); but that it won't be ready until the end of August at the earliest.

**Comment by dsandor716** [comment]
Per last comment Jul 14, please confirm status with Jeremy if it's back on the table at his shop
