### ISSUE TITLE
Record your Learning Page

### ISSUE THREAD

**Issue by MariaChenBCGov** [allanhaggett/learning-curator#131]
Definitely a backlog item... we have info about this in our FAQ page. But if tests show everyone's asking this question and wondering how to do it and not looking at the FAQ, it may be worth it to highlight it in the top nav as a page on  "How to Record Learning" or similar...

**Comment by MariaChenBCGov** [comment]
Aug 6 standup: A "How-to" to be developed by Allan may eliminate the need for this ticket.

**Comment by dsandor716** [comment]
At this early stage, a lower priority and agree with FAQ covering for now

**Comment by MariaChenBCGov** [comment]
2020-09-25 Release Planning: If/when started, need to engage TES, Randy, BI
