### ISSUE TITLE
Consider adding time estimate for Step completion

### ISSUE THREAD

**Issue by MariaChenBCGov** [allanhaggett/learning-curator#138]
"Learners might want to know an estimated time for each step (not just for each resource). I know it’s extra work, and another thing to edit when you add a new resource, but I think it would help to quantify how much time commitment is involved in taking each step."

**Comment by MariaChenBCGov** [comment]
Aug 6 Sprint Planning: "Nice-to-have"
PO: No necessarily need to be in Pilot
If low-hanging fruit, pull into Sprint.

**Comment by dsandor716** [comment]
Still a lower priority.  Group can discuss which sprint we add to but not necc for now as of Sept 1

**Comment by MariaChenBCGov** [comment]
We considered it. Not gonna do it,
