### ISSUE TITLE
Restrict an activity to only be addable to a step once

### ISSUE THREAD

**Issue by ShannonMcFerran** [allanhaggett/learning-curator#16]
When I wasn't sure if a step had been added to a resource, I added it... only to see later that it was a dupe. You can see on this item here, the Foundations pathway/step 1 has been applied twice. https://agent.allankenneth.com/activities/view/255 Is there a way we can show which pathway/steps have been applied in the Path Assignment drop-down button view?

![image](https://user-images.githubusercontent.com/38409344/81869539-0814cc80-9529-11ea-875d-680d50b4b7e6.png)

This is what shows up when I brought up the item later through keyword search: 
![image](https://user-images.githubusercontent.com/38409344/81869628-3b575b80-9529-11ea-81c2-fb3c11e3a995.png)

**Comment by allanhaggett** [comment]
Yeah there's something weird going on here. I'll figure it out!
