### ISSUE TITLE
Enhanced Time Ranges (especially below 1 hour)

### ISSUE THREAD

**Issue by MariaChenBCGov** [allanhaggett/learning-curator#167]
Pilot Feedback:
Refine time ranges

**Comment by shannonator** [comment]
Hi! I'd like to see the following: 
under 10 mins
under 30 mins
under 1 hr... no changes above this.

**Comment by allanhaggett** [comment]
Finished standardizing time ranges with Shannon. Created /activities/list as a curator interface to bulk-update the time ranges on existing activities that don't match with the new standard. Should be put on backlog to have curators go through and assign/reassign time ranges to all activities to match new standards.
