### ISSUE TITLE
Search Function: Return search information on all words in the search string

### ISSUE THREAD

**Issue by MariaChenBCGov** [allanhaggett/learning-curator#171]
Search function: Would like to see it return search information on all words in the search string. "Trust" returns two resources. "Trust in government" returns no values AND "Took a few tries as it first showed as 0 results, and then refreshed my browser and got results" AND Would be useful if search also brought up resources where the word appears in the description and not just the title

**Comment by shannonator** [comment]
- [ ] Search function to find "and" or "&" where user enters "and"

**Comment by shannonator** [comment]
- [ ] Keyword search to search description fields as well as title fields

**Comment by MariaChenBCGov** [comment]
Could be a research SPIKE or EPIC of tasks

**Comment by allanhaggett** [comment]
Decision to install elastic search cakephp plugin and setup an elasticsearch service. Confirm this decision with FuXing and Warren for feasibility on Openshift, but it should be doable. This closes this ticket, but doesn't really implement it. The ticket made me look into the issue and I saw that we would need a more advanced approach (elasticsearch) to create a robust system with advanced features for power users. Implementing this is an epic, I think.
