### ISSUE TITLE
review, approve and add the "context setting" text draft in General Teams channel

### ISSUE THREAD

**Issue by shannonator** [allanhaggett/learning-curator#218]
Just when you thought the sprint was full... Sorry, just thought about this item when we were done the meeting.

**Comment by dsandor716** [comment]
looks good.  I left my comment in Teams

**Comment by allanhaggett** [comment]
Left message in Teams:
https://teams.microsoft.com/l/message/19:806e7ba6694e4bb1865bd3263084f80f@thread.tacv2/1606940964755?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&groupId=08283480-3b33-45cd-ab68-0c9d6ede80e0&parentMessageId=1606940964755&teamName=External%3A%20Learning%20Curator&channelName=General&createdTime=1606940964755
