### ISSUE TITLE
Compose Learning Curation App Source for Dockerfile Build

### ISSUE THREAD

**Issue by fuxingli** [allanhaggett/learning-curator#221]
o	Get the latest Learning Curation App PhP Code/File
o	Get a SQL dump file and create the MySQL database (220KB size currently)

**Comment by allanhaggett** [comment]
Files added in config/ directory. Added a skeleton schema to the config/ directory as well, but there are no users/categories/topics/pathways or any content at all. Will be supplying @Kousthubha-M with the schema-plus-content SQL dump file by uploading that into Teams (or supplying directly as needed)
