### ISSUE TITLE
Investigate the work needed to connect Moodle with PeopleSoft ELM's learning record

### ISSUE THREAD

**Issue by allanhaggett** [allanhaggett/learning-curator#226]
#Note this should be moved to the repo for that project when we can

It should be possible to have PeopleSoft ELM import learner record data from Moodle. There are various levels at which this could happen, depending on resourcing. Ideally, a custom plugin would be programmed for Moodle that would communicate directly with ELM through an API. Failing the resources for this level of integration, having a human-in-the-middle, manual administrative process might be an alternative e.g. an admin person accesses a Moodle dashboard to download data, which is then manually uploaded into ELM; this probably still requires a custom plugin to be written, but might avoid needing to hire a consultant to write the API communication with ELM.

Discuss this more via separate issues.

**Comment by cohiggins** [comment]
Added to Moodle repo
