### ISSUE TITLE
Add a "tour" feature to show people how to use the site

### ISSUE THREAD

**Issue by allanhaggett** [allanhaggett/learning-curator#23]
Use something like: http://bootstraptour.com/ to create a step by step tour of the main interface and how to use it.

**Comment by ShannonMcFerran** [comment]
I need to update the script for the how-to tour. Adding that to the kanban. Thanks! :)

**Comment by shannonator** [comment]
So close to closing! Just need to get it on the site, now. URL for video is here: 
https://youtu.be/ZOJh-tvcxvE

**Comment by allanhaggett** [comment]
Added to a new "How to use" page that is now linked to the left of the FAQ in the main navigation menu.
