### ISSUE TITLE
BUG: Activity page user list is broken

### ISSUE THREAD

**Issue by cohiggins** [allanhaggett/learning-curator#233]
Individual activity pages should list users who have claimed the activity.

**Comment by allanhaggett** [comment]
Since my commit didn't actually fix this issue, we're taking some time to have a consult with another developer to see if we can't get to the real bottom of why the relation between activities and activities_users isn't being made properly.

**Comment by allanhaggett** [comment]
We didn't need the consult meeting with the other developer because I figured this out!
