### ISSUE TITLE
Get Access to SSO

### ISSUE THREAD

**Issue by cohiggins** [allanhaggett/learning-curator#236]
Kousthubha to gain access to single sign-on software. 
(Jared Warren assisting; meeting scheduled for Thursday, Feb 11)

**Comment by Kousthubha-M** [comment]
-Met with citizen services team on leveraging Azure AD as single sign-on.
- Next step is to open/create a consulting order(istore)- Jared is working on it.
- Next some business level decisions has to be made on how data to be used.
