### ISSUE TITLE
Fork thenetworg

### ISSUE THREAD

**Issue by cohiggins** [allanhaggett/learning-curator#265]
**June 14** - Potentially need an additional set of eyes, someone with Composer exp. Jared to look into this.

**Comment by allanhaggett** [comment]
In attempting to figure out how to do this, I've discovered that I probably shouldn't do this at all. I should leave this repo in and call to it from code within my codebase, like in the example in [its readme file](https://github.com/TheNetworg/oauth2-azure)

Closing this and will open a new issue to update the code accordingly.
