### ISSUE TITLE
Presentation ppt for Agency exec

### ISSUE THREAD

**Issue by MariaChenBCGov** [allanhaggett/learning-curator#84]
End date dependant on ADM setting up meeting

DoD

- [x] PowerPoint completed
- [ ] Steve (ED) review
- [x] Team member review

**Comment by MariaChenBCGov** [comment]
- [ ] David to check comments,
- [ ] place or delete added slide, and mark this complete.;
- [ ] Shannon/Steve to review;
- [ ] Deb to review

**Comment by dsandor716** [comment]
With Deb who is now on holiday until Sept 14.  Deadline for using ppt is driven by ADM and we have not heard when she will utilize material or if she wants any revisions so this will stay open until we hear further (i.e. will likely move to next sprint)
